library(RMySQL)
library(plyr)
library(dplyr)
library(httr)
library(jsonlite)
library(lubridate)
library(progress)
library(rvest)
library(dplyr)
library(shiny)
library(ggplot2)
library(plotly)
library(stringr)
library(twitteR)
library(NLP)
library(syuzhet)
library(tm)
library(SnowballC)
library(stringi)
library(topicmodels)
library(syuzhet)
library(ROAuth)
library(RColorBrewer)
library(wordcloud)
library(tm)



source("scripts/databaseHelper.R")
source("scripts/helperFunctions.R")
source("scripts/revenueModelPieCharts.R")